# Generated by Django 4.2.30 on 2026-07-26 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0006_leadactivity_add_real_estate_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('name', models.TextField()),
                ('block_type', models.CharField(choices=[('TOWER', 'Tower'), ('WING', 'Wing'), ('PHASE', 'Phase'), ('SECTOR', 'Sector'), ('BLOCK', 'Block')], max_length=20)),
                ('total_floors', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'real_estate_blocks',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('name', models.TextField()),
                ('project_type', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('MIXED', 'Mixed'), ('PLOTTED', 'Plotted')], max_length=20)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('UNDER_CONSTRUCTION', 'Under Construction'), ('READY_TO_MOVE', 'Ready To Move'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold')], db_index=True, max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('address_line1', models.TextField(blank=True, null=True)),
                ('address_line2', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('postal_code', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('rera_number', models.TextField(blank=True, null=True)),
                ('possession_date', models.DateField(blank=True, null=True)),
                ('created_by_user_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'real_estate_projects',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('unit_type', models.CharField(choices=[('FLAT', 'Flat'), ('VILLA', 'Villa'), ('ROW_HOUSE', 'Row House'), ('PLOT', 'Plot'), ('COMMERCIAL_SHOP', 'Commercial Shop'), ('COMMERCIAL_OFFICE', 'Commercial Office'), ('OTHER', 'Other')], max_length=30)),
                ('unit_number', models.TextField(help_text='Free-text display code, e.g. "A-1203" or "Plot-042"')),
                ('floor_number', models.IntegerField(blank=True, help_text='Can be negative for basement floors', null=True)),
                ('facing', models.CharField(blank=True, choices=[('NORTH', 'North'), ('SOUTH', 'South'), ('EAST', 'East'), ('WEST', 'West'), ('NORTH_EAST', 'North East'), ('NORTH_WEST', 'North West'), ('SOUTH_EAST', 'South East'), ('SOUTH_WEST', 'South West')], max_length=20, null=True)),
                ('configuration', models.TextField(blank=True, help_text='e.g. "2BHK"', null=True)),
                ('carpet_area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('built_up_area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('super_built_up_area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('plot_dimensions', models.TextField(blank=True, help_text='e.g. "30ft x 45ft"', null=True)),
                ('rate_per_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('HELD', 'Held'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('BLOCKED', 'Blocked')], db_index=True, max_length=20)),
                ('amenities', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Tenant custom-field escape hatch', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(blank=True, db_column='block_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='real_estate.block')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='real_estate.project')),
            ],
            options={
                'db_table': 'real_estate_units',
            },
        ),
        migrations.CreateModel(
            name='UnitLead',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('relation_type', models.CharField(choices=[('INTERESTED', 'Interested'), ('SITE_VISIT_SCHEDULED', 'Site Visit Scheduled'), ('SITE_VISIT_DONE', 'Site Visit Done'), ('NEGOTIATING', 'Negotiating'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('CANCELLED', 'Cancelled')], db_index=True, max_length=30)),
                ('booking_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_to', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(db_column='lead_id', on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_units', to='crm.lead')),
                ('unit', models.ForeignKey(db_column='unit_id', on_delete=django.db.models.deletion.CASCADE, related_name='lead_links', to='real_estate.unit')),
            ],
            options={
                'db_table': 'real_estate_unit_leads',
            },
        ),
        migrations.CreateModel(
            name='ProjectInterest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('preferred_unit_type', models.CharField(blank=True, choices=[('FLAT', 'Flat'), ('VILLA', 'Villa'), ('ROW_HOUSE', 'Row House'), ('PLOT', 'Plot'), ('COMMERCIAL_SHOP', 'Commercial Shop'), ('COMMERCIAL_OFFICE', 'Commercial Office'), ('OTHER', 'Other')], max_length=30, null=True)),
                ('preferred_configuration', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_to', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(db_column='lead_id', on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_project_interests', to='crm.lead')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='lead_interests', to='real_estate.project')),
            ],
            options={
                'db_table': 'real_estate_project_interests',
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['tenant_id'], name='idx_re_projects_tenant'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='idx_re_projects_status'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_type'], name='idx_re_projects_type'),
        ),
        migrations.AddField(
            model_name='block',
            name='project',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='real_estate.project'),
        ),
        migrations.AddIndex(
            model_name='unitlead',
            index=models.Index(fields=['tenant_id'], name='idx_re_unit_leads_tenant'),
        ),
        migrations.AddIndex(
            model_name='unitlead',
            index=models.Index(fields=['relation_type'], name='idx_re_unit_leads_relation'),
        ),
        migrations.AddIndex(
            model_name='unitlead',
            index=models.Index(fields=['assigned_to'], name='idx_re_unit_leads_assigned'),
        ),
        migrations.AlterUniqueTogether(
            name='unitlead',
            unique_together={('unit', 'lead')},
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['tenant_id'], name='idx_re_units_tenant'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['project'], name='idx_re_units_project'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['block'], name='idx_re_units_block'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['status'], name='idx_re_units_status'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['unit_type'], name='idx_re_units_type'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['floor_number'], name='idx_re_units_floor'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('project', 'unit_number')},
        ),
        migrations.AddIndex(
            model_name='projectinterest',
            index=models.Index(fields=['tenant_id'], name='idx_re_interests_tenant'),
        ),
        migrations.AddIndex(
            model_name='projectinterest',
            index=models.Index(fields=['assigned_to'], name='idx_re_interests_assigned'),
        ),
        migrations.AlterUniqueTogether(
            name='projectinterest',
            unique_together={('project', 'lead')},
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['tenant_id'], name='idx_re_blocks_tenant'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['project'], name='idx_re_blocks_project'),
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('project', 'name')},
        ),
    ]
