# Generated by Django 4.2.30 on 2026-07-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_type',
            field=models.CharField(choices=[('tower', 'Tower'), ('wing', 'Wing'), ('phase', 'Phase'), ('sector', 'Sector'), ('block', 'Block')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('mixed', 'Mixed'), ('plotted', 'Plotted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('under_construction', 'Under Construction'), ('ready_to_move', 'Ready To Move'), ('completed', 'Completed'), ('on_hold', 'On Hold')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='projectinterest',
            name='preferred_unit_type',
            field=models.CharField(blank=True, choices=[('flat', 'Flat'), ('villa', 'Villa'), ('row_house', 'Row House'), ('plot', 'Plot'), ('commercial_shop', 'Commercial Shop'), ('commercial_office', 'Commercial Office'), ('other', 'Other')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='facing',
            field=models.CharField(blank=True, choices=[('north', 'North'), ('south', 'South'), ('east', 'East'), ('west', 'West'), ('north_east', 'North East'), ('north_west', 'North West'), ('south_east', 'South East'), ('south_west', 'South West')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('held', 'Held'), ('booked', 'Booked'), ('sold', 'Sold'), ('blocked', 'Blocked')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('flat', 'Flat'), ('villa', 'Villa'), ('row_house', 'Row House'), ('plot', 'Plot'), ('commercial_shop', 'Commercial Shop'), ('commercial_office', 'Commercial Office'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='unitlead',
            name='relation_type',
            field=models.CharField(choices=[('interested', 'Interested'), ('site_visit_scheduled', 'Site Visit Scheduled'), ('site_visit_done', 'Site Visit Done'), ('negotiating', 'Negotiating'), ('booked', 'Booked'), ('sold', 'Sold'), ('cancelled', 'Cancelled')], db_index=True, max_length=30),
        ),
    ]
