# Generated by Django 4.2.30 on 2026-07-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_lower_case_enums'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image_zata_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
