# Generated by Django 4.2.26 on 2025-11-06 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('INVOICE', 'Invoice'), ('REFUND', 'Refund'), ('ADVANCE', 'Advance'), ('OTHER', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.TextField(default='INR')),
                ('method', models.TextField(blank=True, null=True)),
                ('reference_no', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLEARED', 'Cleared'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='CLEARED', max_length=20)),
                ('attachment_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(db_column='lead_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crm.lead')),
            ],
            options={
                'db_table': 'payments',
                'indexes': [models.Index(fields=['lead'], name='idx_payments_lead_id'), models.Index(fields=['type'], name='idx_payments_type'), models.Index(fields=['status'], name='idx_payments_status'), models.Index(fields=['date'], name='idx_payments_date')],
            },
        ),
    ]
