# Generated by Django 4.2.30 on 2026-08-18 19:37

import datetime
from django.db import migrations, models
import scheduling.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarPreference',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('default_view', models.CharField(choices=[('MONTH', 'Month'), ('WEEK', 'Week'), ('DAY', 'Day'), ('AGENDA', 'Agenda')], default='MONTH', max_length=8)),
                ('week_starts_on', models.SmallIntegerField(default=1, help_text='0=Sunday, 1=Monday')),
                ('working_hours_start', models.TimeField(default=datetime.time(9, 0))),
                ('working_hours_end', models.TimeField(default=datetime.time(18, 0))),
                ('working_days', models.JSONField(blank=True, default=scheduling.models.default_working_days, help_text='[1,2,3,4,5] = Mon-Fri')),
                ('visible_layers', models.JSONField(blank=True, default=scheduling.models.default_visible_layers, help_text="['meetings','tasks','follow_ups']")),
                ('visible_user_ids', models.JSONField(blank=True, default=list, help_text='Team members whose lanes are toggled on.')),
                ('default_meeting_duration_minutes', models.PositiveIntegerField(default=30)),
                ('show_declined', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'calendar_preferences',
            },
        ),
        migrations.AddConstraint(
            model_name='calendarpreference',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'user_id'), name='uniq_calendar_pref'),
        ),
    ]
