# Generated by Django 4.2.26 on 2025-11-06 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('location', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(blank=True, db_column='lead_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='crm.lead')),
            ],
            options={
                'db_table': 'meetings',
                'indexes': [models.Index(fields=['lead'], name='idx_meetings_lead_id'), models.Index(fields=['start_at'], name='idx_meetings_start_at')],
            },
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.CheckConstraint(check=models.Q(('end_at__gt', models.F('start_at'))), name='meetings_end_after_start'),
        ),
        migrations.AlterUniqueTogether(
            name='meeting',
            unique_together={('title', 'start_at')},
        ),
    ]
