# Generated by Django 4.2.30 on 2026-08-18 19:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_leadactivity_add_real_estate_type'),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingAttendee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField(blank=True, db_index=True, help_text='SuperAdmin user UUID for an internal attendee.', null=True)),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('role', models.CharField(choices=[('ORGANIZER', 'Organizer'), ('REQUIRED', 'Required'), ('OPTIONAL', 'Optional')], default='REQUIRED', max_length=12)),
                ('response_status', models.CharField(choices=[('NEEDS_ACTION', 'No response'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('TENTATIVE', 'Maybe')], db_index=True, default='NEEDS_ACTION', max_length=14)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('is_organizer', models.BooleanField(default=False)),
                ('notify', models.BooleanField(default=True, help_text='Generate reminder rows for this attendee.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'meeting_attendees',
            },
        ),
        migrations.CreateModel(
            name='MeetingReminder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('minutes_before', models.PositiveIntegerField()),
                ('method', models.CharField(choices=[('IN_APP', 'In-app'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp')], default='IN_APP', max_length=12)),
                ('for_attendees', models.BooleanField(default=True, help_text='True = every attendee with notify=True; False = organiser only.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'meeting_reminders',
            },
        ),
        migrations.RemoveConstraint(
            model_name='meeting',
            name='meetings_end_after_start',
        ),
        migrations.RemoveConstraint(
            model_name='meeting',
            name='unique_meeting_per_tenant',
        ),
        migrations.AddField(
            model_name='meeting',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='meeting',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='cancelled_by_user_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='color',
            field=models.CharField(blank=True, default='', help_text='Optional colour-token override (e.g. "violet"). Empty means derive the colour from meeting_type.', max_length=20),
        ),
        migrations.AddField(
            model_name='meeting',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='conference_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='external_calendar_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='external_event_id',
            field=models.CharField(blank=True, db_index=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='external_provider',
            field=models.CharField(blank=True, db_index=True, help_text='GOOGLE | CALDAV | MICROSOFT | COMPOSIO_GOOGLE ... Null = CRM-only meeting.', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='external_sync',
            field=models.JSONField(blank=True, help_text='Provider-specific sync metadata that must NOT require a migration to extend: {"account_id":..., "connected_account_id":..., "etag":..., "sync_token":..., "ical_uid":..., "html_link":..., "sequence":..., "raw_updated":...}', null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('MEETING', 'Meeting'), ('CALL', 'Call'), ('DEMO', 'Demo'), ('SITE_VISIT', 'Site Visit'), ('FOLLOW_UP', 'Follow Up'), ('INTERNAL', 'Internal'), ('OTHER', 'Other')], db_index=True, default='MEETING', max_length=20),
        ),
        migrations.AddField(
            model_name='meeting',
            name='recurrence_end_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Denormalised UTC instant of the last possible occurrence (resolved from UNTIL or COUNT at save time). Null = open-ended.', null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='recurrence_exdates',
            field=models.JSONField(blank=True, default=list, help_text='List of ISO-8601 UTC occurrence start instants removed from the series (RFC 5545 EXDATE).'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='recurrence_original_start',
            field=models.DateTimeField(blank=True, help_text='RFC 5545 RECURRENCE-ID. On an override row, the original UTC start of the occurrence in the parent series that this row replaces.', null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='recurrence_rule',
            field=models.TextField(blank=True, help_text='RFC 5545 RRULE without the "RRULE:" prefix, e.g. "FREQ=WEEKLY;BYDAY=MO,WE;UNTIL=20261231T183000Z". Null means a single, non-recurring meeting.', null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='recurring_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='meetings.meeting'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('TENTATIVE', 'Tentative'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show')], db_index=True, default='SCHEDULED', max_length=20),
        ),
        migrations.AddField(
            model_name='meeting',
            name='sync_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='meeting',
            name='sync_status',
            field=models.CharField(choices=[('NOT_SYNCED', 'Not synced'), ('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], db_index=True, default='NOT_SYNCED', max_length=12),
        ),
        migrations.AddField(
            model_name='meeting',
            name='timezone',
            field=models.CharField(default='UTC', help_text='IANA timezone the meeting was authored in (e.g. "Asia/Kolkata"). start_at/end_at remain UTC instants; this is what the UI renders in and what an RRULE is expanded against so DST shifts stay correct.', max_length=64),
        ),
        migrations.AddField(
            model_name='meeting',
            name='transparency',
            field=models.CharField(choices=[('OPAQUE', 'Busy'), ('TRANSPARENT', 'Free')], default='OPAQUE', help_text='OPAQUE blocks the owner in free/busy; TRANSPARENT does not.', max_length=12),
        ),
        migrations.AddField(
            model_name='meeting',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Stable iCalendar-style UID. Survives external round-trips; used as the RFC 5545 UID when pushed to Google/CalDAV and as the React key prefix.'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='visibility',
            field=models.CharField(choices=[('DEFAULT', 'Default'), ('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='DEFAULT', help_text='PRIVATE meetings are redacted to "Busy" for anyone who is not the owner or an attendee.', max_length=10),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['tenant_id', 'owner_user_id', 'start_at'], name='idx_meetings_tenant_owner_st'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['tenant_id', 'start_at', 'end_at'], name='idx_meetings_tenant_window'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['recurring_parent', 'recurrence_original_start'], name='idx_meetings_override'),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.CheckConstraint(check=models.Q(('end_at__gte', models.F('start_at'))), name='meetings_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.UniqueConstraint(condition=models.Q(('recurring_parent__isnull', False)), fields=('recurring_parent', 'recurrence_original_start'), name='uniq_meeting_override_per_occurrence'),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.UniqueConstraint(condition=models.Q(('external_event_id__isnull', False)), fields=('tenant_id', 'external_provider', 'external_event_id'), name='uniq_meeting_external_event'),
        ),
        migrations.AddField(
            model_name='meetingreminder',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_rules', to='meetings.meeting'),
        ),
        migrations.AddField(
            model_name='meetingattendee',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_invites', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='meetingattendee',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='meetings.meeting'),
        ),
        migrations.AddConstraint(
            model_name='meetingreminder',
            constraint=models.UniqueConstraint(fields=('meeting', 'minutes_before', 'method'), name='uniq_meeting_reminder_rule'),
        ),
        migrations.AddIndex(
            model_name='meetingattendee',
            index=models.Index(fields=['tenant_id', 'user_id'], name='idx_mtg_att_tenant_user'),
        ),
        migrations.AddIndex(
            model_name='meetingattendee',
            index=models.Index(fields=['meeting', 'response_status'], name='idx_mtg_att_response'),
        ),
        migrations.AddConstraint(
            model_name='meetingattendee',
            constraint=models.UniqueConstraint(condition=models.Q(('user_id__isnull', False)), fields=('meeting', 'user_id'), name='uniq_attendee_user_per_meeting'),
        ),
        migrations.AddConstraint(
            model_name='meetingattendee',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('meeting', 'email'), name='uniq_attendee_email_per_meeting'),
        ),
        migrations.AddConstraint(
            model_name='meetingattendee',
            constraint=models.CheckConstraint(check=models.Q(('user_id__isnull', False), ('lead__isnull', False), models.Q(('email', ''), _negated=True), _connector='OR'), name='meeting_attendee_has_identity'),
        ),
    ]
