# Generated by Django 4.2.30 on 2026-08-20 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_leadactivity_add_real_estate_type'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskChecklistItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('text', models.TextField()),
                ('is_done', models.BooleanField(default=False)),
                ('order_index', models.IntegerField(default=0)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'task_checklist_items',
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='is_all_day',
            field=models.BooleanField(default=False, help_text='True when start_date/due_date carry a date only; the UI renders them against ``timezone`` rather than as clock times.'),
        ),
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.JSONField(blank=True, default=list, help_text='Free-form list of string labels, e.g. ["urgent", "documents"].'),
        ),
        migrations.AddField(
            model_name='task',
            name='order_index',
            field=models.IntegerField(db_index=True, default=0, help_text='Manual sort position within a board/list. Set by the reorder endpoint; lower sorts first.'),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_end_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Denormalised UTC instant of the last possible occurrence (resolved from UNTIL/COUNT at save time). Null = open-ended.', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='recurring_parent',
            field=models.ForeignKey(blank=True, help_text='The first task in a recurring series. Set on every spawned occurrence; null on the series head itself.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='related_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Primary key of the related_type object. Always resolved tenant-scoped; an id belonging to another tenant resolves to nothing rather than leaking a name.', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='related_type',
            field=models.CharField(choices=[('NONE', 'Not linked'), ('LEAD', 'Lead'), ('PROJECT', 'Project'), ('UNIT', 'Unit'), ('MEETING', 'Meeting')], db_index=True, default='NONE', help_text='Which CRM object this task is about: LEAD, PROJECT, UNIT, MEETING, or NONE for a standalone task.', max_length=16),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_minutes_before',
            field=models.PositiveIntegerField(blank=True, help_text='Minutes before due_date to raise a notifications.Reminder. Null = no reminder. Materialised by tasks.tasks.materialize_task_reminders and delivered by the existing notifications.tasks.dispatch_due_reminders beat job.', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='rrule',
            field=models.TextField(blank=True, help_text='RFC 5545 RRULE without the "RRULE:" prefix, e.g. "FREQ=WEEKLY;BYDAY=MO". Parsed by meetings.recurrence. Null = a one-off task. Completing a recurring task spawns the next occurrence instead of ending the series.', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='snoozed_until',
            field=models.DateTimeField(blank=True, help_text='Set by the snooze endpoint; the reminder materialiser skips a task until this instant has passed.', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='UTC instant the work is meant to start. Null = start whenever.', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='timezone',
            field=models.CharField(default='UTC', help_text='IANA timezone this task was authored in (e.g. "Asia/Kolkata"). start_date/due_date stay UTC instants; this mirrors meetings.Meeting.timezone and is what an rrule expands against.', max_length=64),
        ),
        migrations.AlterField(
            model_name='task',
            name='checklist',
            field=models.JSONField(blank=True, help_text='DEPRECATED raw JSON checklist. Superseded by TaskChecklistItem rows; kept (and still written by the data migration reverse) only so the change is reversible. Read checklist_items instead.', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='lead',
            field=models.ForeignKey(blank=True, db_column='lead_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.lead'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant_id', 'related_type', 'related_id'], name='idx_tasks_related'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant_id', 'assignee_user_id', 'due_date'], name='idx_tasks_my_day'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant_id', 'order_index'], name='idx_tasks_order'),
        ),
        migrations.AddField(
            model_name='taskchecklistitem',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='tasks.task'),
        ),
        migrations.AddIndex(
            model_name='taskchecklistitem',
            index=models.Index(fields=['tenant_id'], name='idx_task_cli_tenant'),
        ),
        migrations.AddIndex(
            model_name='taskchecklistitem',
            index=models.Index(fields=['task', 'order_index'], name='idx_task_cli_order'),
        ),
    ]
