# Generated by Django 4.2.26 on 2025-11-06 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='Unnamed')),
                ('phone', models.TextField()),
                ('email', models.TextField(blank=True, null=True)),
                ('company', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('value_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('value_currency', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('owner_user_id', models.UUIDField(blank=True, null=True)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('address_line1', models.TextField(blank=True, null=True)),
                ('address_line2', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('postal_code', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'leads',
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CALL', 'Call'), ('EMAIL', 'Email'), ('MEETING', 'Meeting'), ('NOTE', 'Note'), ('SMS', 'SMS'), ('OTHER', 'Other')], max_length=20)),
                ('content', models.TextField(blank=True, null=True)),
                ('happened_at', models.DateTimeField()),
                ('by_user_id', models.UUIDField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('file_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lead_activities',
                'ordering': ['-happened_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadOrder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('position', models.DecimalField(decimal_places=3, max_digits=12)),
                ('board_id', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lead_orders',
            },
        ),
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('order_index', models.IntegerField()),
                ('color_hex', models.TextField(blank=True, null=True)),
                ('is_won', models.BooleanField(default=False)),
                ('is_lost', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lead_statuses',
                'ordering': ['order_index'],
                'indexes': [models.Index(fields=['order_index'], name='idx_lead_statuses_order_index')],
            },
        ),
        migrations.AddConstraint(
            model_name='leadstatus',
            constraint=models.CheckConstraint(check=models.Q(('is_won', True), ('is_lost', True), _negated=True), name='lead_statuses_won_lost_check'),
        ),
        migrations.AddField(
            model_name='leadorder',
            name='lead',
            field=models.ForeignKey(db_column='lead_id', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='leadorder',
            name='status',
            field=models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.CASCADE, related_name='lead_orders', to='crm.leadstatus'),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='lead',
            field=models.ForeignKey(db_column='lead_id', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.ForeignKey(blank=True, db_column='status_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.leadstatus'),
        ),
        migrations.AddIndex(
            model_name='leadorder',
            index=models.Index(fields=['status', 'position'], name='idx_lead_orders_status_id_pos'),
        ),
        migrations.AddIndex(
            model_name='leadorder',
            index=models.Index(fields=['lead'], name='idx_lead_orders_lead_id'),
        ),
        migrations.AlterUniqueTogether(
            name='leadorder',
            unique_together={('lead', 'status')},
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['lead'], name='idx_lead_activities_lead_id'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['type'], name='idx_lead_activities_type'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['happened_at'], name='idx_lead_activities__at'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='idx_leads_status_id'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['priority'], name='idx_leads_priority'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['owner_user_id'], name='idx_leads_owner_user_id'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone'], name='idx_leads_phone'),
        ),
    ]
