# Generated by Django 4.2.26 on 2025-11-23
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Custom fields for storing dynamic key-value pairs', null=True),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to'], name='idx_leads_assigned_to'),
        ),
    ]
