# Generated by Django 4.2.26 on 2025-11-24
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_lead_assigned_to_lead_metadata'),
    ]

    operations = [
        # Create LeadCustomField model
        migrations.CreateModel(
            name='LeadCustomField',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('field_name', models.TextField(help_text='Internal field name (key)')),
                ('field_label', models.TextField(help_text='Display label for the field')),
                ('field_type', models.CharField(
                    choices=[
                        ('TEXT', 'Text'),
                        ('NUMBER', 'Number'),
                        ('EMAIL', 'Email'),
                        ('PHONE', 'Phone'),
                        ('DATE', 'Date'),
                        ('DATETIME', 'Date Time'),
                        ('DROPDOWN', 'Dropdown'),
                        ('MULTISELECT', 'Multi Select'),
                        ('CHECKBOX', 'Checkbox'),
                        ('URL', 'URL'),
                        ('TEXTAREA', 'Text Area'),
                    ],
                    default='TEXT',
                    max_length=20
                )),
                ('is_required', models.BooleanField(default=False)),
                ('default_value', models.TextField(blank=True, null=True)),
                ('options', models.JSONField(
                    blank=True,
                    help_text='Options for dropdown/multiselect fields (array of strings)',
                    null=True
                )),
                ('placeholder', models.TextField(blank=True, null=True)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lead_custom_fields',
                'ordering': ['display_order', 'field_label'],
                'indexes': [
                    models.Index(fields=['tenant_id'], name='idx_lead_custom_fields_tenant'),
                    models.Index(fields=['tenant_id', 'is_active'], name='idx_lead_custom_fields_active'),
                    models.Index(fields=['display_order'], name='idx_lead_custom_fields_order'),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name='leadcustomfield',
            constraint=models.UniqueConstraint(
                fields=('tenant_id', 'field_name'),
                name='unique_custom_field_per_tenant'
            ),
        ),

        # Create LeadFieldVisibility model
        migrations.CreateModel(
            name='LeadFieldVisibility',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('field_name', models.TextField(help_text='Standard field name from Lead model')),
                ('is_visible', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lead_field_visibility',
                'ordering': ['display_order', 'field_name'],
                'indexes': [
                    models.Index(fields=['tenant_id'], name='idx_lead_field_vis_tenant'),
                    models.Index(fields=['tenant_id', 'is_visible'], name='idx_lead_field_vis_visible'),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name='leadfieldvisibility',
            constraint=models.UniqueConstraint(
                fields=('tenant_id', 'field_name'),
                name='unique_field_visibility_per_tenant'
            ),
        ),
    ]
