# Generated by Django 4.2.30 on 2026-05-30 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_lead_lead_score_lead_leads_score_range_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAttachment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('file_name', models.TextField()),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('zata_video_id', models.UUIDField(blank=True, null=True)),
                ('download_url', models.TextField()),
                ('uploaded_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(db_column='lead_id', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm.lead')),
            ],
            options={
                'db_table': 'lead_attachments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id'], name='idx_lead_attachments_tenant'), models.Index(fields=['lead'], name='idx_lead_attachments_lead_id')],
            },
        ),
    ]
