# Generated by Django 4.2.30 on 2026-08-18 19:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComposioAuthConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Stable, non-sequential identifier safe to expose in API URLs.', unique=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Tenant that owns this auth config. NULL = platform-wide default.', null=True)),
                ('toolkit_slug', models.CharField(db_index=True, help_text='Composio toolkit slug, uppercase (e.g. GMAIL, NOTION, GOOGLEDRIVE, GOOGLECALENDAR).', max_length=100)),
                ('auth_config_id', models.CharField(help_text='Composio auth config id ("ac_..."). Unique across the platform.', max_length=64, unique=True)),
                ('auth_scheme', models.CharField(choices=[('OAUTH2', 'OAuth 2.0'), ('OAUTH1', 'OAuth 1.0'), ('API_KEY', 'API Key'), ('BEARER_TOKEN', 'Bearer Token'), ('BASIC', 'Basic Auth'), ('NO_AUTH', 'No Auth')], default='OAUTH2', help_text='Auth scheme Composio reports for this config.', max_length=20)),
                ('is_composio_managed', models.BooleanField(default=True, help_text='True when Composio owns the OAuth app (no client credentials of ours).')),
                ('name', models.CharField(help_text='Display name shown to tenant admins.', max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether users may create new connections against this config.')),
                ('restrict_to_tools', models.JSONField(blank=True, help_text='Allowlist of tool slugs this config may execute through /execute/. Empty or NULL means no tool may be executed (fail closed).', null=True)),
                ('default_tool_versions', models.JSONField(blank=True, help_text='Map of tool slug to pinned Composio tool version, e.g. {"GMAIL_GET_PROFILE": "20251111_00"}.', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Raw non-secret auth-config payload from Composio (expected_input_fields, scopes). Scrubbed before persisting; never contains secrets.', null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='When we last reconciled this row against Composio.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'composio_auth_configs',
                'ordering': ['toolkit_slug', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ComposioConnection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Stable, non-sequential identifier used in API URLs and OAuth return links.', unique=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant ID for multi-tenancy.')),
                ('user_id', models.UUIDField(db_index=True, help_text='CRM user who owns this connection.')),
                ('scope', models.CharField(choices=[('USER', 'Per user'), ('TENANT', 'Tenant-wide (shared)')], default='USER', help_text='USER = private to the owner. TENANT = shared with everyone in the tenant.', max_length=10)),
                ('composio_user_id', models.CharField(db_index=True, help_text='Composio entity id: "{namespace}:{tenant_id}:{user_id|tenant}". The only isolation boundary Composio enforces between end users.', max_length=200)),
                ('toolkit_slug', models.CharField(db_index=True, help_text='Denormalised from auth_config for cheap filtering (e.g. GMAIL).', max_length=100)),
                ('connected_account_id', models.CharField(blank=True, help_text='Composio connected account id ("ca_..."). link() returns it BEFORE the user authorises, so it is set from initiate time onward.', max_length=64, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INITIALIZING', 'Initializing'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked'), ('DELETED', 'Deleted')], db_index=True, default='PENDING', help_text='Local mirror of the Composio connected-account status.', max_length=20)),
                ('alias', models.CharField(blank=True, help_text='User-facing label (e.g. "Sales inbox"). Passed to Composio as alias.', max_length=200, null=True)),
                ('account_label', models.CharField(blank=True, help_text='Third-party account identifier surfaced by the provider (e.g. the connected Gmail address), when Composio returns it. Display only, never a credential.', max_length=320, null=True)),
                ('granted_scopes', models.JSONField(blank=True, help_text='OAuth scopes Composio reports as granted, when available.', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Credential expiry as reported by Composio, when available. We do NOT hold the token.', null=True)),
                ('connected_at', models.DateTimeField(blank=True, help_text='When the account first became ACTIVE.', null=True)),
                ('last_status_check_at', models.DateTimeField(blank=True, help_text='Last time we polled Composio for status.', null=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time a tool was executed with this account.', null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, help_text='When this connection was disconnected/deleted.', null=True)),
                ('last_error', models.TextField(blank=True, help_text='Last error message from Composio, if any.', null=True)),
                ('last_error_at', models.DateTimeField(blank=True, help_text='When the last error occurred.', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Raw NON-SECRET Composio payload (toolkit meta, account type, link expiry). Always passed through composio_client.scrub() first - state.val is dropped entirely.', null=True)),
                ('created_by_user_id', models.UUIDField(blank=True, help_text='User who initiated the connection (differs from user_id for TENANT scope).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_config', models.ForeignKey(db_column='auth_config_id', help_text='Auth config this connection was created against.', on_delete=django.db.models.deletion.PROTECT, related_name='connections', to='integrations.composioauthconfig')),
            ],
            options={
                'db_table': 'composio_connections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComposioToolkit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(db_index=True, help_text='Composio toolkit slug, uppercase (GMAIL, NOTION, GOOGLEDRIVE, GOOGLECALENDAR).', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable toolkit name.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Short description from Composio meta.', null=True)),
                ('logo_url', models.URLField(blank=True, help_text='Toolkit logo URL from Composio meta.', max_length=500, null=True)),
                ('categories', models.JSONField(blank=True, help_text='Category slugs reported by Composio.', null=True)),
                ('auth_schemes', models.JSONField(blank=True, help_text='All auth schemes the toolkit supports.', null=True)),
                ('composio_managed_auth_schemes', models.JSONField(blank=True, help_text='Schemes Composio manages the OAuth app for. Non-empty means one-click connect with no credentials of ours.', null=True)),
                ('no_auth', models.BooleanField(default=False, help_text='Toolkit requires no authentication at all.')),
                ('tools_count', models.IntegerField(default=0, help_text='Number of tools, from Composio meta.')),
                ('triggers_count', models.IntegerField(default=0, help_text='Number of triggers, from Composio meta.')),
                ('is_enabled', models.BooleanField(db_index=True, default=False, help_text='Whether tenants may connect this toolkit. Default False - we opt toolkits in explicitly rather than exposing the whole Composio catalogue.')),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Pinned to the top of the catalogue grid.')),
                ('sort_order', models.IntegerField(default=1000, help_text='Manual ordering within the catalogue.')),
                ('metadata', models.JSONField(blank=True, help_text='Raw non-secret toolkit payload from Composio.', null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='When this row was last refreshed from Composio.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'composio_toolkits',
                'ordering': ['-is_featured', 'sort_order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='idx_cmp_toolkit_slug'), models.Index(fields=['is_enabled', 'is_featured'], name='idx_cmp_toolkit_visible')],
            },
        ),
        migrations.CreateModel(
            name='ComposioLinkState',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(db_index=True, help_text='Opaque nonce (secrets.token_urlsafe(32)) echoed back on the callback URL.', max_length=64, unique=True)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant that started the flow.')),
                ('user_id', models.UUIDField(db_index=True, help_text='User that started the flow.')),
                ('toolkit_slug', models.CharField(help_text='Toolkit being connected (for logging and the return redirect).', max_length=100)),
                ('return_to', models.CharField(blank=True, help_text='Relative frontend path to return the user to. Validated against settings.COMPOSIO_RETURN_TO_ALLOWLIST; never an absolute URL.', max_length=500, null=True)),
                ('link_expires_at', models.DateTimeField(blank=True, help_text='expires_at returned by Composio for the auth link, when available.', null=True)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='When this nonce stops being accepted (now + COMPOSIO_LINK_TTL_SECONDS).')),
                ('consumed_at', models.DateTimeField(blank=True, help_text='When the nonce was redeemed. Non-NULL = spent, replay rejected.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(db_column='connection_id', help_text='Connection this hosted-auth round trip belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='link_states', to='integrations.composioconnection')),
            ],
            options={
                'db_table': 'composio_link_states',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComposioConnectionEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant ID for multi-tenancy.')),
                ('event_type', models.CharField(choices=[('INITIATED', 'Connection initiated'), ('CALLBACK', 'Callback received'), ('ACTIVATED', 'Connection activated'), ('FAILED', 'Connection failed'), ('REFRESHED', 'Re-authorised'), ('DISABLED', 'Disabled'), ('ENABLED', 'Enabled'), ('DISCONNECTED', 'Disconnected'), ('STATUS_SYNC', 'Status synchronised'), ('TOOL_EXECUTED', 'Tool executed'), ('WEBHOOK', 'Webhook received'), ('ERROR', 'Error')], db_index=True, help_text='What happened.', max_length=20)),
                ('actor_user_id', models.UUIDField(blank=True, help_text='User who caused the event. NULL for system/webhook-driven events.', null=True)),
                ('message', models.TextField(blank=True, help_text='Human-readable summary.', null=True)),
                ('payload', models.JSONField(blank=True, help_text='Scrubbed context (tool slug, status transition, error code). Never secrets.', null=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, help_text='Client IP for user-initiated events.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('connection', models.ForeignKey(db_column='connection_id', help_text='Connection this event belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='integrations.composioconnection')),
            ],
            options={
                'db_table': 'composio_connection_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='composioauthconfig',
            index=models.Index(fields=['toolkit_slug'], name='idx_cmp_authcfg_toolkit'),
        ),
        migrations.AddIndex(
            model_name='composioauthconfig',
            index=models.Index(fields=['tenant_id'], name='idx_cmp_authcfg_tenant'),
        ),
        migrations.AddIndex(
            model_name='composioauthconfig',
            index=models.Index(fields=['tenant_id', 'toolkit_slug'], name='idx_cmp_authcfg_lookup'),
        ),
        migrations.AddIndex(
            model_name='composioauthconfig',
            index=models.Index(fields=['is_active'], name='idx_cmp_authcfg_active'),
        ),
        migrations.AddConstraint(
            model_name='composioauthconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant_id__isnull', True)), fields=('toolkit_slug',), name='uniq_cmp_authcfg_global_per_toolkit'),
        ),
        migrations.AddConstraint(
            model_name='composioauthconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant_id__isnull', False)), fields=('tenant_id', 'toolkit_slug'), name='uniq_cmp_authcfg_tenant_per_toolkit'),
        ),
        migrations.AddIndex(
            model_name='composiolinkstate',
            index=models.Index(fields=['expires_at'], name='idx_cmp_state_expiry'),
        ),
        migrations.AddIndex(
            model_name='composiolinkstate',
            index=models.Index(fields=['tenant_id', 'user_id'], name='idx_cmp_state_tenant_user'),
        ),
        migrations.AddIndex(
            model_name='composioconnectionevent',
            index=models.Index(fields=['tenant_id'], name='idx_cmp_evt_tenant'),
        ),
        migrations.AddIndex(
            model_name='composioconnectionevent',
            index=models.Index(fields=['connection', '-created_at'], name='idx_cmp_evt_conn_recent'),
        ),
        migrations.AddIndex(
            model_name='composioconnectionevent',
            index=models.Index(fields=['tenant_id', 'event_type', '-created_at'], name='idx_cmp_evt_lookup'),
        ),
        migrations.AddIndex(
            model_name='composioconnection',
            index=models.Index(fields=['tenant_id'], name='idx_cmp_conn_tenant'),
        ),
        migrations.AddIndex(
            model_name='composioconnection',
            index=models.Index(fields=['user_id'], name='idx_cmp_conn_user'),
        ),
        migrations.AddIndex(
            model_name='composioconnection',
            index=models.Index(fields=['status'], name='idx_cmp_conn_status'),
        ),
        migrations.AddIndex(
            model_name='composioconnection',
            index=models.Index(fields=['toolkit_slug'], name='idx_cmp_conn_toolkit'),
        ),
        migrations.AddIndex(
            model_name='composioconnection',
            index=models.Index(fields=['composio_user_id'], name='idx_cmp_conn_entity'),
        ),
        migrations.AddIndex(
            model_name='composioconnection',
            index=models.Index(fields=['tenant_id', 'user_id', 'toolkit_slug'], name='idx_cmp_conn_lookup'),
        ),
        migrations.AddIndex(
            model_name='composioconnection',
            index=models.Index(fields=['tenant_id', 'status'], name='idx_cmp_conn_tenant_status'),
        ),
        migrations.AddConstraint(
            model_name='composioconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['DELETED', 'REVOKED', 'FAILED']), _negated=True), fields=('tenant_id', 'user_id', 'toolkit_slug', 'alias'), name='uniq_cmp_conn_live_per_user_toolkit_alias'),
        ),
    ]
