# Generated by Django 4.2.30 on 2026-08-18 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_backfill_attendee_organizer'),
        ('crm', '0006_leadactivity_add_real_estate_type'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reminder',
            name='uniq_active_lead_reminder',
        ),
        migrations.AddField(
            model_name='reminder',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_reminders', to='meetings.meeting'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='method',
            field=models.CharField(default='IN_APP', max_length=12),
        ),
        migrations.AddField(
            model_name='reminder',
            name='occurrence_start_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='UTC start of the specific meeting occurrence this reminder belongs to. Null for lead follow-ups.', null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='subject_type',
            field=models.CharField(db_index=True, default='LEAD_FOLLOW_UP', max_length=32),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='crm.lead'),
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.UniqueConstraint(condition=models.Q(('lead__isnull', False), ('meeting__isnull', True), ('status__in', ['PENDING', 'PROCESSING'])), fields=('tenant_id', 'lead', 'recipient_user_id'), name='uniq_active_lead_reminder'),
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.UniqueConstraint(condition=models.Q(('meeting__isnull', False), ('status__in', ['PENDING', 'PROCESSING'])), fields=('tenant_id', 'meeting', 'occurrence_start_at', 'recipient_user_id', 'offset_minutes'), name='uniq_active_meeting_reminder'),
        ),
    ]
