# Generated by Django 4.2.30 on 2026-08-20 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_crm_wide_tasks'),
        ('notifications', '0002_meeting_reminders'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reminder',
            name='uniq_active_lead_reminder',
        ),
        migrations.AddField(
            model_name='reminder',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='tasks.task'),
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.UniqueConstraint(condition=models.Q(('lead__isnull', False), ('meeting__isnull', True), ('status__in', ['PENDING', 'PROCESSING']), ('task__isnull', True)), fields=('tenant_id', 'lead', 'recipient_user_id'), name='uniq_active_lead_reminder'),
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'PROCESSING']), ('task__isnull', False)), fields=('tenant_id', 'task', 'recipient_user_id', 'offset_minutes'), name='uniq_active_task_reminder'),
        ),
    ]
