# Generated by Django 4.2.30 on 2026-05-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeleCMICredential',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, unique=True)),
                ('app_id', models.CharField(help_text='TeleCMI App ID (appid)', max_length=100)),
                ('secret_encrypted', models.TextField(help_text='Encrypted TeleCMI app secret')),
                ('sbc_region', models.CharField(choices=[('sg', 'Asia (Singapore)'), ('ind', 'India'), ('us', 'Americas'), ('uk', 'Europe')], default='ind', help_text='SBC region for WebRTC SDK login', max_length=10)),
                ('default_caller_id', models.CharField(blank=True, help_text='Default caller ID displayed on outgoing calls', max_length=30, null=True)),
                ('webhook_secret', models.CharField(blank=True, help_text='Optional shared secret to verify incoming TeleCMI webhooks', max_length=128, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'telephony_credentials',
                'indexes': [models.Index(fields=['tenant_id'], name='idx_tel_cred_tenant')],
            },
        ),
        migrations.CreateModel(
            name='TeleCMIAgent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('telecmi_user_id', models.CharField(help_text='TeleCMI user ID (e.g. 103_1111112)', max_length=100)),
                ('password_encrypted', models.TextField(help_text='Encrypted TeleCMI agent password')),
                ('cached_token', models.CharField(blank=True, help_text='Cached login token from /v2/user/login', max_length=200, null=True)),
                ('token_obtained_at', models.DateTimeField(blank=True, help_text='When the cached token was last obtained', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'telephony_agents',
                'indexes': [models.Index(fields=['tenant_id', 'user_id'], name='idx_tel_agent_tenant_user')],
                'unique_together': {('tenant_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('from_number', models.CharField(blank=True, max_length=30, null=True)),
                ('to_number', models.CharField(db_index=True, max_length=30)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=10)),
                ('lead_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('sent_by_user_id', models.UUIDField(blank=True, null=True)),
                ('telecmi_response', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'telephony_sms_logs',
                'indexes': [models.Index(fields=['tenant_id'], name='idx_tel_sms_tenant'), models.Index(fields=['to_number'], name='idx_tel_sms_to'), models.Index(fields=['lead_id'], name='idx_tel_sms_lead'), models.Index(fields=['tenant_id', 'created_at'], name='idx_tel_sms_tenant_time')],
            },
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('cmiuid', models.CharField(db_index=True, help_text='TeleCMI unique call identifier', max_length=100)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('call_type', models.CharField(choices=[('missed', 'Missed'), ('answered', 'Answered')], max_length=10)),
                ('from_number', models.CharField(db_index=True, max_length=30)),
                ('to_number', models.CharField(db_index=True, max_length=30)),
                ('duration', models.IntegerField(default=0, help_text='Total call duration in seconds')),
                ('billed_sec', models.IntegerField(default=0, help_text='Billed duration in seconds')),
                ('rate', models.DecimalField(decimal_places=4, default=0, help_text='Per-second call rate in USD', max_digits=10)),
                ('caller_name', models.CharField(blank=True, max_length=200, null=True)),
                ('telecmi_notes', models.JSONField(blank=True, help_text='Notes array from TeleCMI CDR response', null=True)),
                ('call_time', models.DateTimeField(db_index=True, help_text='When the call occurred (UTC)')),
                ('lead_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('agent_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('synced_via', models.CharField(default='webhook', help_text='webhook or manual_sync', max_length=20)),
                ('activity_created', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'telephony_call_logs',
                'indexes': [models.Index(fields=['tenant_id'], name='idx_tel_calls_tenant'), models.Index(fields=['tenant_id', 'direction'], name='idx_tel_calls_direction'), models.Index(fields=['tenant_id', 'call_type'], name='idx_tel_calls_type'), models.Index(fields=['tenant_id', 'call_time'], name='idx_tel_calls_time'), models.Index(fields=['from_number'], name='idx_tel_calls_from'), models.Index(fields=['to_number'], name='idx_tel_calls_to'), models.Index(fields=['lead_id'], name='idx_tel_calls_lead')],
                'unique_together': {('tenant_id', 'cmiuid')},
            },
        ),
    ]
