# Generated by Django 4.2.30 on 2026-05-29 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telecmicredential',
            options={'ordering': ['-created_at']},
        ),
    ]
