# Generated by Django 4.2.30 on 2026-06-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0002_add_credential_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telecmiagent',
            name='cached_token',
            field=models.TextField(blank=True, help_text='Cached login token from /v2/user/login', null=True),
        ),
    ]
