# Generated by Django 4.2.30 on 2026-06-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0003_alter_cached_token_to_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='recording_file',
            field=models.CharField(blank=True, help_text='TeleCMI recording filename (e.g. demo_1111113.wav)', max_length=300, null=True),
        ),
    ]
