# Generated by Django 4.2.30 on 2026-07-30 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_leadactivity_add_real_estate_type'),
        ('telephony', '0005_calllog_analytics_and_campaigns'),
    ]

    operations = [
        migrations.AddField(
            model_name='telecmicampaign',
            name='source_group',
            field=models.ForeignKey(blank=True, db_column='source_group_id', help_text='CRM lead group this campaign is seeded from, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telephony_campaigns', to='crm.leadgroup'),
        ),
    ]
