# Generated by Django 4.2.30 on 2026-08-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0008_zata_recording_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='telecmicredential',
            name='default_agent_id',
            field=models.CharField(blank=True, default='', help_text='Shared TeleCMI extension (e.g. 103_1111112) that every user of this tenant logs the browser softphone in with when they have no personal TeleCMIAgent row. The app_id/secret are tenant-wide, so this extension is too.', max_length=100),
        ),
        migrations.AddField(
            model_name='telecmicredential',
            name='default_agent_password_encrypted',
            field=models.TextField(blank=True, default='', help_text="Password for `default_agent_id`, encrypted with this tenant's DEK — the same envelope scheme as `secret_encrypted`."),
        ),
        migrations.AddField(
            model_name='telecmicredential',
            name='default_agent_token',
            field=models.TextField(blank=True, help_text='Cached /v2/user/login token for the shared default extension.', null=True),
        ),
        migrations.AddField(
            model_name='telecmicredential',
            name='default_agent_token_obtained_at',
            field=models.DateTimeField(blank=True, help_text='When default_agent_token was last obtained.', null=True),
        ),
        migrations.AddField(
            model_name='telecmicredential',
            name='default_agent_verified_at',
            field=models.DateTimeField(blank=True, help_text='Last time TeleCMI accepted default_agent_id/password.', null=True),
        ),
        migrations.AddField(
            model_name='telecmicredential',
            name='default_agent_verify_error',
            field=models.TextField(blank=True, default='', help_text='Why the last verification of the default extension did not succeed. Set when TeleCMI was unreachable at save time, so the credential is stored but flagged rather than silently trusted.'),
        ),
    ]
