# Generated by Django 4.2.30 on 2026-08-19 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0009_tenant_default_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeleCMICallingProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('label', models.CharField(help_text='Human name for this calling identity, e.g. "Sales line".', max_length=150)),
                ('telecmi_user_id', models.CharField(help_text='TeleCMI extension this profile logs in as, e.g. 103_1111112.', max_length=100)),
                ('password_encrypted', models.TextField(blank=True, default='', help_text="SIP password for the extension, encrypted with this tenant's DEK.")),
                ('dek_wrapped', models.TextField(blank=True, default='', help_text="This tenant's data-encryption key, itself encrypted with TELECMI_MASTER_KEY. Shared with the tenant credential row when one exists.")),
                ('caller_id', models.CharField(blank=True, help_text='PSTN number this profile should present. Pushed to TeleCMI with POST /v2/set_callerid when a session resolves to this profile — caller ID is a property of the extension, not of a single call.', max_length=30, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Used by any user of this tenant with no explicit assignment. At most one profile per tenant may set this.')),
                ('is_active', models.BooleanField(default=True)),
                ('cached_token', models.TextField(blank=True, help_text='Cached /v2/user/login token for this extension.', null=True)),
                ('token_obtained_at', models.DateTimeField(blank=True, null=True)),
                ('caller_id_pushed_value', models.CharField(blank=True, help_text='Last caller ID we successfully pushed to TeleCMI for this extension. TeleCMI exposes no "currently active" flag, so this is the only record of it — and it keeps the softphone path from re-pushing an unchanged value on every page load.', max_length=30, null=True)),
                ('verified_at', models.DateTimeField(blank=True, help_text='Last time TeleCMI accepted this extension and password.', null=True)),
                ('verify_error', models.TextField(blank=True, default='', help_text='Why the last verification did not succeed. Set when TeleCMI was unreachable, so the profile is stored but flagged rather than silently trusted.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'telephony_calling_profiles',
                'ordering': ['-is_default', 'label'],
            },
        ),
        migrations.CreateModel(
            name='TeleCMIProfileAssignment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(db_column='profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='telephony.telecmicallingprofile')),
            ],
            options={
                'db_table': 'telephony_calling_profile_assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='telecmicallingprofile',
            index=models.Index(fields=['tenant_id'], name='idx_tel_profile_tenant'),
        ),
        migrations.AddConstraint(
            model_name='telecmicallingprofile',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'telecmi_user_id'), name='uniq_tel_profile_tenant_ext'),
        ),
        migrations.AddConstraint(
            model_name='telecmicallingprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('tenant_id',), name='uniq_tel_profile_one_default'),
        ),
        migrations.AddIndex(
            model_name='telecmiprofileassignment',
            index=models.Index(fields=['tenant_id', 'user_id'], name='idx_tel_profile_assign'),
        ),
        migrations.AddConstraint(
            model_name='telecmiprofileassignment',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'user_id'), name='uniq_tel_profile_assign_user'),
        ),
    ]
