# Generated by Django 4.2.30 on 2026-08-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0010_calling_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10)),
                ('fcm_token', models.CharField(max_length=512)),
                ('app', models.CharField(default='crmflutter', help_text='Which client registered this token, e.g. crmflutter or celiyocrmmobileapp', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'telephony_device_tokens',
                'indexes': [models.Index(fields=['tenant_id', 'user_id'], name='idx_tel_devtok_user')],
                'unique_together': {('tenant_id', 'fcm_token')},
            },
        ),
    ]
