# Hand-written to match telephony.models.TeleCMIWebhookLog.
#
# NOT generated by `makemigrations`: this checkout's .venv is broken (its
# python.exe points at another user's profile, and its Django install is
# missing django.contrib.staticfiles among others), so neither
# `makemigrations` nor the test suite can run here. Run
# `python manage.py makemigrations telephony --check --dry-run` on a working
# environment before deploying; it should report no changes.
#
# Additive only: creates one new table, touches no existing row.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0011_devicetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeleCMIWebhookLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('event_type', models.CharField(blank=True, default='', max_length=64)),
                ('raw_payload', models.JSONField(default=dict)),
                ('matched', models.BooleanField(db_index=True, default=False)),
                ('normalized_event', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'telephony_webhook_logs',
                'indexes': [
                    models.Index(
                        fields=['tenant_id', 'matched', '-created_at'],
                        name='idx_tel_whlog_unmatched',
                    )
                ],
            },
        ),
    ]
